### PR TITLE
Add littlefs-disk-img-viewer to README

### PR DESCRIPTION
**Pull request by tniessen**
This is a tool that I've been working on. It should be capable of opening littlefs disk images up to a size of 4 GiB and allows browsing the folder structure, "downloading" files from the file system, etc.

The tool doesn't support all of the features of littlefs yet (e.g., viewing folder attributes), but it's [getting there](https://github.com/tniessen/littlefs-disk-img-viewer).

### CODE REVIEW

**Comment by ShaharHD** [comment]
any reason why not merged yet?

**Comment by geky** [comment]
Hi @tniessen, this really interesting work! Thanks for creating a PR.

Sorry about taking so long to address this, this deserved some sort of status update earlier. Unfortunately I don't think the README is the correct place for this. I have had plans to create a wiki/website with a page for community projects, but I haven't been able to get to it yet due to other things. Until that is ready I'm going to keep this PR open.

**Comment by geky** [comment]
I've made one tweak to link to the repo (https://github.com/tniessen/littlefs-disk-img-viewer) instead of directly to the tool. I think the README in the repo currently has a better introduction/explanation about the tool that would be interesting for first time viewers (I suspect most people clicking through this link).

Let me know if you have any issues with this.

**Comment by tniessen** [comment]
That's perfect, thank you.

**Pull request merged**
