### PR TITLE
Grow block count to configured value when LFS_M_GROW mount flag is set

### PR DESCRIPTION
**Pull request by kaetemi**
See #279

### CODE REVIEW

**Comment by kaetemi** [comment]
Test
```
    err = lfs_mount(&lfs, &cfg);
    lfs_unmount(&lfs);

    // fail without flag
    cfg.block_count += 1;
    err = lfs_mount(&lfs, &cfg);
    assert(err);

    // success with flag
    cfg.flags |= LFS_M_GROW;
    err = lfs_mount(&lfs, &cfg);
    assert(err == LFS_ERR_OK);
    lfs_unmount(&lfs);

    // cannot shrink
    cfg.flags = 0;
    cfg.block_count -= 1;
    err = lfs_mount(&lfs, &cfg);
    assert(err);

    // cannot shrink with flag either
    cfg.flags |= LFS_M_GROW;
    err = lfs_mount(&lfs, &cfg);
    assert(err);
```

**Comment by geky** [comment]
Hi @kaetemi, thanks for the PR. This is a great implementation, but unfortunately I'm against the resizing behavior being implicit. I've added a comment with more info to the related issue https://github.com/littlefs-project/littlefs/issues/279.

I can modify this to be in a separate `lfs_fs_grow` function if you don't beat me to it.

I'm also hoping to address https://github.com/littlefs-project/littlefs/issues/349 in the next minor release, which means `lfs_mount` will probably have quite a few changes.

**Comment by geky** [comment]
I've gone ahead and added `lfs_fs_grow` to #753, thanks for the original PR. I believe #753 replaces this now, but let me know if I'm missing anything.

**Comment by geky** [comment]
Closing as this has been merged into https://github.com/littlefs-project/littlefs/pull/872 and should be mainlined shortly as a part of https://github.com/littlefs-project/littlefs/pull/877.

Feel free to reopen if you think I missed anything and thanks again for the PR!

**Pull request closed without merging**
