### PR TITLE
Restructure littlefs to not use recursion, measure stack usage

### LINKED ISSUE #417: What is the maximum stack depth of LFS?
I see a recursive function in the file system.

### PR DESCRIPTION
**Pull request by geky**
This PR restructures the internals of littlefs a bit to completely avoid recursion. In theory the design of littlefs uses strictly bounded RAM, though it was written using some recursive functions, and at least one code path relied on tail-call optimization for bounded RAM consumption, which isn't guaranteed in standard C.

This broke down into three pieces of logic that used recursion:

1. lfs_dir_commit/lfs_fs_relocate - 84da4c0b1af465014e80cb48fca26d407a4ab214

   The biggest culprit of recursion was the relocation logic responsible for moving metadata to new blocks when a block goes bad or has high wear. The reason is because this occurs deep within the commit logic and is inherently recursive (any commit can require relocation, which needs to commit to fix the relocation!)
   
   This required quite a bit of restructuring, inverting most of the commit logic so that relocations occur on an outer loop that invokes the core commit logic. The commit logic ends up with several new entry points that "fall back" to outer loops under different error conditions, with the top level loop being a full `lfs_fs_deorphan` pass.
   
2. lfs_file_read/write/flush - fedf646c79c44061ca62f5ae3019fe1198ec07d2

   A bit easier to solve, `lfs_file_read` and `lfs_file_write` sometimes need to flush state from other `lfs_file_read`/`lfs_file_write` calls. The only problem being that `lfs_file_flush` calls `lfs_file_read`/`lfs_file_write` to do the flush!
   
   This was easy to solve with an extra set of `lfs_file_flushedread`/`lfs_file_flushedwrite` entry points that avoid this. Note that
   this code path couldn't actually occur normally outside of filesystem bugs.

3. lfs_dir_traverse - 8109f282668d0396c1a8df05d38ed215b0b8feac

   `lfs_dir_traverse` was also a bit tricky. It's inherently recursive, but has a strict upper bound of 4 calls (a traverse with a filter with a move with a filter).
   
   I tried a few different things, but it was difficult to unroll things without an extra ~1KiB of code cost. The solution here
   is to add an explicit, bounded stack (just an array of state), which turned out to not increase the code cost too badly. 
   
   I suspect this hints that modeling traversals with callbacks is a poor choice for a non-recursive code, so this may be worth implementing differently at some point in the future.

---

This PR also adds a few more scripts and utilities to help analyze builds and compare different implementations:
- `make code` or `./scripts/code.py` - Reports the code size of functions
- `make data` or `./scripts/data.py` - Reports any data sections, this should always be zero for littlefs
- `make stack` or `./scripts/stack.py` - Reports stack frames and maximum stack usage of functions
- `make structs` or `./scripts/structs.py` - Reports the size of any public structs 

For example:

``` bash
$ make stack STACKFLAGS+='-L1'
```

<details>
<summary> Output </summary>

```
./scripts/stack.py lfs.ci lfs_util.ci -S
name                                   frame   limit
lfs_dir_close                              0       0
lfs_dir_tell                               0       0
lfs_file_size                              0       0
lfs_file_tell                              0       0
lfs_fs_preporphans                         0       0
lfs_fs_size_count                          0       0
lfs_pair_isnull                            0       0
lfs_tag_dsize                              0       0
lfs_alloc_lookahead                        8       8
lfs_bd_erase.isra                          8       8
lfs_cache_zero.isra                        8       8
lfs_deinit                                 8       8
lfs_dir_commit_size                        8       8
lfs_gstate_xor                             8       8
lfs_pair_cmp                               8       8
lfs_crc                                   16      16
lfs_dir_traverse_filter                   16      16
lfs_gstate_hasmovehere                     8      16
lfs_unmount                                8      16
lfs_ctz_index.isra                        24      24
lfs_init                                  16      24
lfs_bd_read                               64      64
lfs_fs_parent_match                       40     104
lfs_bd_cmp.constprop                      64     128
lfs_ctz_find.constprop                    64     128
lfs_dir_getslice                          64     128
lfs_ctz_traverse                          72     136
lfs_dir_get                               24     152
lfs_dir_find_match                        32     160
lfs_dir_fetchmatch                       112     176
lfs_bd_flush                              56     184
lfs_dir_getgstate                         40     192
lfs_dir_getinfo                           40     192
lfs_dir_getread.constprop                 64     192
lfs_dir_fetch                             24     200
lfs_dir_rewind                             8     208
lfs_bd_prog                               32     216
lfs_dir_read                              24     224
lfs_fs_pred                               32     232
lfs_dir_seek                              40     240
lfs_fs_parent                             64     240
lfs_file_flushedread                      56     248
lfs_dir_commitprog                        40     256
lfs_dir_find                              96     272
lfs_fs_rawtraverse                        88     288
lfs_dir_commitcrc                         80     296
lfs_fs_traverse                            8     296
lfs_fs_rawsize                            16     304
lfs_mount                                112     304
lfs_fs_size                                8     312
lfs_alloc                                 32     320
lfs_dir_commitattr                        64     320
lfs_dir_open                              48     320
lfs_dir_commit_commit                      8     328
lfs_stat                                  56     328
lfs_dir_traverse.constprop               272     336
lfs_getattr                               64     336
lfs_dir_alloc                             32     352
lfs_file_relocate                         56     376
lfs_dir_compact                          136     472
lfs_file_flushedwrite                     96     472
lfs_dir_split                             96     568
lfs_file_flush                           112     584
lfs_file_rawseek                          16     600
lfs_file_read                             24     608
lfs_file_rewind                            8     608
lfs_file_seek                              8     608
lfs_file_rawwrite                         40     624
lfs_file_write                             8     632
lfs_file_truncate                         48     672
lfs_dir_relocatingcommit                 128     696
lfs_dir_orphaningcommit                  136     832
lfs_fs_deorphan                          160     992
lfs_dir_commit                             8    1000
lfs_dir_drop                              24    1024
lfs_file_rawsync                          48    1048
lfs_fs_forceconsistency                   48    1048
lfs_file_sync                              8    1056
lfs_commitattr                            64    1064
lfs_file_rawclose                         16    1064
lfs_file_close                             8    1072
lfs_removeattr                            16    1080
lfs_setattr                               24    1088
lfs_format                               104    1104
lfs_file_rawopencfg                       64    1128
lfs_file_open                             16    1144
lfs_file_opencfg                          16    1144
lfs_remove                               128    1176
lfs_mkdir                                184    1232
lfs_rename                               216    1264
TOTAL                                   4248    1264
```

</details>

Or with callgraph info:

``` bash
$ make stack STACKFLAGS+='-L1'
```

<details>
<summary> Output </summary>

``` 
./scripts/stack.py lfs.ci lfs_util.ci -S -L1
name                                   frame   limit
lfs_dir_close                              0       0
lfs_dir_tell                               0       0
lfs_file_size                              0       0
lfs_file_tell                              0       0
lfs_fs_preporphans                         0       0
lfs_fs_size_count                          0       0
lfs_pair_isnull                            0       0
lfs_tag_dsize                              0       0
lfs_alloc_lookahead                        8       8
lfs_bd_erase.isra                          8       8
lfs_cache_zero.isra                        8       8
lfs_deinit                                 8       8
lfs_dir_commit_size                        8       8
'-> lfs_tag_dsize                          0       0
lfs_gstate_xor                             8       8
lfs_pair_cmp                               8       8
lfs_crc                                   16      16
lfs_dir_traverse_filter                   16      16
lfs_gstate_hasmovehere                     8      16
'-> lfs_pair_cmp                           8       8
lfs_unmount                                8      16
'-> lfs_deinit                             8       8
lfs_ctz_index.isra                        24      24
lfs_init                                  16      24
|-> lfs_cache_zero.isra                    8       8
'-> lfs_deinit                             8       8
lfs_bd_read                               64      64
lfs_fs_parent_match                       40     104
|-> lfs_pair_cmp                           8       8
'-> lfs_bd_read                           64      64
lfs_bd_cmp.constprop                      64     128
'-> lfs_bd_read                           64      64
lfs_ctz_find.constprop                    64     128
|-> lfs_ctz_index.isra                    24      24
'-> lfs_bd_read                           64      64
lfs_dir_getslice                          64     128
|-> lfs_tag_dsize                          0       0
|-> lfs_gstate_hasmovehere                 8      16
'-> lfs_bd_read                           64      64
lfs_ctz_traverse                          72     136
|-> lfs_ctz_index.isra                    24      24
'-> lfs_bd_read                           64      64
lfs_dir_get                               24     152
'-> lfs_dir_getslice                      64     128
lfs_dir_find_match                        32     160
'-> lfs_bd_cmp.constprop                  64     128
lfs_dir_fetchmatch                       112     176
|-> lfs_tag_dsize                          0       0
|-> lfs_crc                               16      16
|-> lfs_gstate_hasmovehere                 8      16
'-> lfs_bd_read                           64      64
lfs_bd_flush                              56     184
|-> lfs_cache_zero.isra                    8       8
'-> lfs_bd_cmp.constprop                  64     128
lfs_dir_getgstate                         40     192
|-> lfs_gstate_xor                         8       8
'-> lfs_dir_get                           24     152
lfs_dir_getinfo                           40     192
'-> lfs_dir_get                           24     152
lfs_dir_getread.constprop                 64     192
'-> lfs_dir_getslice                      64     128
lfs_dir_fetch                             24     200
'-> lfs_dir_fetchmatch                   112     176
lfs_dir_rewind                             8     208
'-> lfs_dir_fetch                         24     200
lfs_bd_prog                               32     216
'-> lfs_bd_flush                          56     184
lfs_dir_read                              24     224
|-> lfs_dir_getinfo                       40     192
'-> lfs_dir_fetch                         24     200
lfs_fs_pred                               32     232
|-> lfs_pair_isnull                        0       0
|-> lfs_pair_cmp                           8       8
'-> lfs_dir_fetch                         24     200
lfs_dir_seek                              40     240
|-> lfs_pair_cmp                           8       8
'-> lfs_dir_fetch                         24     200
lfs_fs_parent                             64     240
|-> lfs_pair_isnull                        0       0
'-> lfs_dir_fetchmatch                   112     176
lfs_file_flushedread                      56     248
|-> lfs_bd_read                           64      64
|-> lfs_ctz_find.constprop                64     128
'-> lfs_dir_getread.constprop             64     192
lfs_dir_commitprog                        40     256
|-> lfs_crc                               16      16
'-> lfs_bd_prog                           32     216
lfs_dir_find                              96     272
|-> lfs_dir_get                           24     152
'-> lfs_dir_fetchmatch                   112     176
lfs_fs_rawtraverse                        88     288
|-> lfs_pair_isnull                        0       0
|-> lfs_ctz_traverse                      72     136
|-> lfs_dir_get                           24     152
'-> lfs_dir_fetch                         24     200
lfs_dir_commitcrc                         80     296
|-> lfs_crc                               16      16
|-> lfs_bd_read                           64      64
|-> lfs_bd_flush                          56     184
'-> lfs_bd_prog                           32     216
lfs_fs_traverse                            8     296
'-> lfs_fs_rawtraverse                    88     288
lfs_fs_rawsize                            16     304
'-> lfs_fs_rawtraverse                    88     288
lfs_mount                                112     304
|-> lfs_pair_isnull                        0       0
|-> lfs_init                              16      24
|-> lfs_dir_get                           24     152
|-> lfs_dir_fetchmatch                   112     176
'-> lfs_dir_getgstate                     40     192
lfs_fs_size                                8     312
'-> lfs_fs_rawsize                        16     304
lfs_alloc                                 32     320
'-> lfs_fs_rawtraverse                    88     288
lfs_dir_commitattr                        64     320
|-> lfs_tag_dsize                          0       0
|-> lfs_bd_read                           64      64
'-> lfs_dir_commitprog                    40     256
lfs_dir_open                              48     320
|-> lfs_dir_get                           24     152
|-> lfs_dir_fetch                         24     200
'-> lfs_dir_find                          96     272
lfs_dir_commit_commit                      8     328
'-> lfs_dir_commitattr                    64     320
lfs_stat                                  56     328
|-> lfs_dir_getinfo                       40     192
'-> lfs_dir_find                          96     272
lfs_dir_traverse.constprop               272     336
|-> lfs_tag_dsize                          0       0
'-> lfs_bd_read                           64      64
lfs_getattr                               64     336
|-> lfs_dir_get                           24     152
|-> lfs_dir_fetch                         24     200
'-> lfs_dir_find                          96     272
lfs_dir_alloc                             32     352
|-> lfs_bd_read                           64      64
'-> lfs_alloc                             32     320
lfs_file_relocate                         56     376
|-> lfs_bd_erase.isra                      8       8
|-> lfs_cache_zero.isra                    8       8
|-> lfs_bd_read                           64      64
|-> lfs_dir_getread.constprop             64     192
|-> lfs_bd_prog                           32     216
'-> lfs_alloc                             32     320
lfs_dir_compact                          136     472
|-> lfs_pair_isnull                        0       0
|-> lfs_bd_erase.isra                      8       8
|-> lfs_gstate_xor                         8       8
|-> lfs_pair_cmp                           8       8
|-> lfs_dir_getgstate                     40     192
|-> lfs_dir_commitprog                    40     256
|-> lfs_dir_commitcrc                     80     296
|-> lfs_alloc                             32     320
|-> lfs_dir_commitattr                    64     320
'-> lfs_dir_traverse.constprop           272     336
lfs_file_flushedwrite                     96     472
|-> lfs_bd_erase.isra                      8       8
|-> lfs_cache_zero.isra                    8       8
|-> lfs_ctz_index.isra                    24      24
|-> lfs_bd_read                           64      64
|-> lfs_ctz_find.constprop                64     128
|-> lfs_bd_prog                           32     216
|-> lfs_alloc                             32     320
'-> lfs_file_relocate                     56     376
lfs_dir_split                             96     568
|-> lfs_pair_cmp                           8       8
|-> lfs_dir_alloc                         32     352
'-> lfs_dir_compact                      136     472
lfs_file_flush                           112     584
|-> lfs_bd_flush                          56     184
|-> lfs_file_flushedread                  56     248
|-> lfs_file_relocate                     56     376
'-> lfs_file_flushedwrite                 96     472
lfs_file_rawseek                          16     600
'-> lfs_file_flush                       112     584
lfs_file_read                             24     608
|-> lfs_file_flushedread                  56     248
'-> lfs_file_flush                       112     584
lfs_file_rewind                            8     608
'-> lfs_file_rawseek                      16     600
lfs_file_seek                              8     608
'-> lfs_file_rawseek                      16     600
lfs_file_rawwrite                         40     624
|-> lfs_file_flushedwrite                 96     472
'-> lfs_file_flush                       112     584
lfs_file_write                             8     632
'-> lfs_file_rawwrite                     40     624
lfs_file_truncate                         48     672
|-> lfs_ctz_find.constprop                64     128
|-> lfs_file_flush                       112     584
|-> lfs_file_rawseek                      16     600
'-> lfs_file_rawwrite                     40     624
lfs_dir_relocatingcommit                 128     696
|-> lfs_gstate_xor                         8       8
|-> lfs_pair_cmp                           8       8
|-> lfs_dir_getgstate                     40     192
|-> lfs_dir_fetch                         24     200
|-> lfs_fs_pred                           32     232
|-> lfs_dir_commitcrc                     80     296
|-> lfs_fs_rawsize                        16     304
|-> lfs_dir_commitattr                    64     320
|-> lfs_dir_traverse.constprop           272     336
|-> lfs_dir_compact                      136     472
'-> lfs_dir_split                         96     568
lfs_dir_orphaningcommit                  136     832
|-> lfs_fs_preporphans                     0       0
|-> lfs_pair_cmp                           8       8
|-> lfs_gstate_hasmovehere                 8      16
|-> lfs_dir_getgstate                     40     192
|-> lfs_fs_pred                           32     232
|-> lfs_fs_parent                         64     240
|-> lfs_file_relocate                     56     376
|-> lfs_file_flush                       112     584
'-> lfs_dir_relocatingcommit             128     696
lfs_fs_deorphan                          160     992
|-> lfs_fs_preporphans                     0       0
|-> lfs_pair_isnull                        0       0
|-> lfs_gstate_hasmovehere                 8      16
|-> lfs_dir_get                           24     152
|-> lfs_dir_getgstate                     40     192
|-> lfs_dir_fetch                         24     200
|-> lfs_fs_parent                         64     240
'-> lfs_dir_orphaningcommit              136     832
lfs_dir_commit                             8    1000
|-> lfs_dir_orphaningcommit              136     832
'-> lfs_fs_deorphan                      160     992
lfs_dir_drop                              24    1024
|-> lfs_dir_getgstate                     40     192
'-> lfs_dir_commit                         8    1000
lfs_file_rawsync                          48    1048
|-> lfs_pair_isnull                        0       0
|-> lfs_file_flush                       112     584
'-> lfs_dir_commit                         8    1000
lfs_fs_forceconsistency                   48    1048
|-> lfs_dir_fetch                         24     200
|-> lfs_fs_deorphan                      160     992
'-> lfs_dir_commit                         8    1000
lfs_file_sync                              8    1056
'-> lfs_file_rawsync                      48    1048
lfs_commitattr                            64    1064
|-> lfs_dir_fetch                         24     200
|-> lfs_dir_find                          96     272
'-> lfs_dir_commit                         8    1000
lfs_file_rawclose                         16    1064
'-> lfs_file_rawsync                      48    1048
lfs_file_close                             8    1072
'-> lfs_file_rawclose                     16    1064
lfs_removeattr                            16    1080
'-> lfs_commitattr                        64    1064
lfs_setattr                               24    1088
'-> lfs_commitattr                        64    1064
lfs_format                               104    1104
|-> lfs_deinit                             8       8
|-> lfs_init                              16      24
|-> lfs_dir_fetch                         24     200
|-> lfs_dir_alloc                         32     352
'-> lfs_dir_commit                         8    1000
lfs_file_rawopencfg                       64    1128
|-> lfs_cache_zero.isra                    8       8
|-> lfs_dir_get                           24     152
|-> lfs_dir_find                          96     272
|-> lfs_dir_commit                         8    1000
|-> lfs_fs_forceconsistency               48    1048
'-> lfs_file_rawclose                     16    1064
lfs_file_open                             16    1144
'-> lfs_file_rawopencfg                   64    1128
lfs_file_opencfg                          16    1144
'-> lfs_file_rawopencfg                   64    1128
lfs_remove                               128    1176
|-> lfs_fs_preporphans                     0       0
|-> lfs_dir_get                           24     152
|-> lfs_dir_fetch                         24     200
|-> lfs_fs_pred                           32     232
|-> lfs_dir_find                          96     272
|-> lfs_dir_commit                         8    1000
|-> lfs_dir_drop                          24    1024
'-> lfs_fs_forceconsistency               48    1048
lfs_mkdir                                184    1232
|-> lfs_fs_preporphans                     0       0
|-> lfs_dir_fetch                         24     200
|-> lfs_dir_find                          96     272
|-> lfs_dir_alloc                         32     352
|-> lfs_dir_commit                         8    1000
'-> lfs_fs_forceconsistency               48    1048
lfs_rename                               216    1264
|-> lfs_fs_preporphans                     0       0
|-> lfs_pair_cmp                           8       8
|-> lfs_dir_get                           24     152
|-> lfs_dir_fetch                         24     200
|-> lfs_fs_pred                           32     232
|-> lfs_dir_find                          96     272
|-> lfs_dir_commit                         8    1000
|-> lfs_dir_drop                          24    1024
'-> lfs_fs_forceconsistency               48    1048
TOTAL                                   4248    1264
```
</details>

Note this depends on the `-fstack-usage` flag introduced in GCC 10.

Also, if you're curious what the deepest call is in littlefs after this change:

``` bash
$ ./scripts/stack.py lfs.ci lfs_util.ci -L -s
name                                                         frame   limit
lfs_rename                                                     216    1264
|-> lfs_fs_forceconsistency                                     48    1048
|   |-> lfs_dir_commit                                           8    1000
|   |   |-> lfs_fs_deorphan                                    160     992
|   |   |   |-> lfs_dir_orphaningcommit                        136     832
|   |   |   |   |-> lfs_dir_relocatingcommit                   128     696
|   |   |   |   |   |-> lfs_dir_split                           96     568
|   |   |   |   |   |   |-> lfs_dir_compact                    136     472
|   |   |   |   |   |   |   |-> lfs_dir_traverse.constprop     272     336
|   |   |   |   |   |   |   |   |-> lfs_bd_read                 64      64
```

---

These changes do come with a code cost, as some of the recursion allowed a bit better code reuse:

<table>
<thead>
<tr>
<th align=left>Configuration</th>
<th align=right>Code</th>
<th align=right>Stack</th>
<th align=right>Structs</th>
</tr>
</thead>
<tbody>
<tr>
<td align=left>Default</td>
<td align=right>
14656 B (+5.1%)
</td>
<td align=right>
1264 B (-∞%)
</td>
<td align=right>
772 B (+0.0%)
</td>
</tr>
<tr>
<td align=left>Readonly</td>
<td align=right>
5346 B (+0.0%)
</td>
<td align=right>
336 B (+0.0%)
</td>
<td align=right>
772 B (+0.0%)
</td>
</tr>
<tr>
<td align=left>Threadsafe</td>
<td align=right>
15586 B (+4.7%)
</td>
<td align=right>
1264 B (-∞%)
</td>
<td align=right>
780 B (+0.0%)
</td>
</tr>
<tr>
<td align=left>Migrate</td>
<td align=right>
16308 B (+4.4%)
</td>
<td align=right>
1528 B (-∞%)
</td>
<td align=right>
776 B (+0.0%)
</td>
</tr>
<tr>
<td align=left>Error-asserts</td>
<td align=right>
15264 B (+5.0%)
</td>
<td align=right>
1256 B (-∞%)
</td>
<td align=right>
772 B (+0.0%)
</td>
</tr>
</tbody>
</table>

Should resolve #417

### CODE REVIEW

**Comment by dpgeorge** [comment]
> 3\. `lfs_dir_traverse` was also a bit tricky. It's inherently recursive, but has a strict upper bound of 4 calls (a traverse with a filter with a move with a filter).

Did you see #621 (I'm sure you did), in particular:
> Yet, despite (2), the overall CPU time only decrease by 75%, leaving the huge number of times lfs_dir_traverse is called.
We analyze the call graph and saw that 4 levels of recursive calls of lfs_dir_traverse are done during compaction.
A O(n^4) is obviously a problem...

And then:

> Yet, for the particular case of cb=lfs_dir_traverse_filter for [3] and [4], we saw that all the calls are useless ... The shortcut of this particular case reduce the number of lfs_dir_traverse calls by 97.8%

So I assume the optimisation being talked about there is to cut down this recursion significantly.  But it looks like that optimisation cannot be applied generally, is that true?  It would be great to see this optimisation applied because it really does help to improve littlefs performance.

**Comment by geky** [comment]
> Did you see https://github.com/littlefs-project/littlefs/pull/621 (I'm sure you did), in particular:

Ah I did, and was actually just re-reading it, but haven't been able to fully understand/provide useful feedback to the proposal yet. I hadn't realized it was related to this, thanks for pointing that out.

> A O(n^4) is obviously a problem...

It actually should be "only" O(n^2+n^2) = O(n^2), since a LFS_FROM_MOVE tag can only occur once in an attribute list ([here](https://github.com/littlefs-project/littlefs/blob/master/lfs.c#L3362), the LFS_FROM_* tags can't occur on disk).

That being said, this O(n^2) loop has been be a big mistake. It's something I'm actively exploring, with at least one potential prototype, but it's quite difficult to solve. I'd be quite interested to know @invoxiaamo's ideas, but that might be a discussion for that PR.

This is the main reason behind https://github.com/littlefs-project/littlefs/issues/203

> Yet, for the particular case of cb=lfs_dir_traverse_filter for [3] and [4], we saw that all the calls are useless

I was initially skeptical but looking into it a bit more this might be true. If so this would be a great improvement to have and might be able to reduce the stack usage in lfs_dir_traverse down to 3 frames.

**Comment by dpgeorge** [comment]
Regarding this PR: in general I think it's a good idea to eliminate the use of recursion, or at least have more control over the recursion.  If it's fully eliminated it might be interesting to add a check to CI to ensure it's not added again accidentally (and that will limit the features that can be added in the future, which IMO is a good thing).

As for code size increase: we do use littlefs in a bootloader and it needs to be small, but it's in read-only mode so looks like that won't change with this PR.

**Comment by geky** [comment]
It's not a hard error, but CI results in the "show all checks" panel would show "∞ B" instead of "1696 B", unfortunately GitHub has made these hard to view recently. At the very least it would be difficult to ignore [come release time](https://github.com/geky/littlefs-test-repo/releases/tag/v2.4.9). But making it a hard error is an even better idea.

**Comment by benpicco** [comment]
Hm this actually *increases* stack usage when tested with RIOT's [`tests/pkg_littlefs2`](https://github.com/RIOT-OS/RIOT/tree/master/tests/pkg_littlefs2) on the `native` target

#### v2.4.2 

```
START
main(): This is RIOT! (Version: 2022.07-devel-309-gf3c36-pkg/littlefs2-bump)
........
OK (8 tests)
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2508 }]}
```

#### v2.5.0

(via https://github.com/RIOT-OS/RIOT/pull/18049)

```
START
main(): This is RIOT! (Version: 2022.07-devel-309-gf3c36-pkg/littlefs2-bump)
........
OK (8 tests)
{ "threads": [{ "name": "idle", "stack_size": 8192, "stack_used": 436 }]}
{ "threads": [{ "name": "main", "stack_size": 12288, "stack_used": 2828 }]}
```

84da4c0b1af465014e80cb48fca26d407a4ab214 bumps the `main` stack usage to 2700 bytes, then 8109f282668d0396c1a8df05d38ed215b0b8feac pushes it to 2828

**Comment by warasilapm** [comment]
@geky I recognize this was a difficult and sizeable undertaking and I am extremely thankful for the work you've done to accomplish this. I had a whole class of bugs based around stack usage within littlefs in one of our applications on a RAM constrained device where every bit of stack per task counted. I ended up guessing and checking the RAM usage but was always worried about usage during relocation for worn blocks down the road. Having this be deterministic is exactly what I was hoping for out of littlefs.

**Pull request merged**
